runtime: python39  # Utilisez Python 3.9 (ou une version compatible)
entrypoint: gunicorn -w 4 -b :$PORT app:app  # Lancer votre app avec Gunicorn

handlers:
  - url: /static
    static_dir: static  # Définir le dossier pour les fichiers statiques
  - url: /.*
    script: auto  # Tout le reste sera géré par Flask

env_variables:  # Variables d'environnement (si nécessaires)
  SECRET_KEY: "SECRET_KEY: "f527baec8ff944bfaeaaf2c7c48f7a0838f39b1e5724f7e418a48a9024c44c87"
  DATABASE_URL: "sqlite:///mlflow.db"

instance_class: F2  # (Optionnel) Type d'instance. F2 est une petite machine.
